- Symmetirics matrics
    + 대각선을 기준으로 대칭인 행렬
- Identity matrics 
    + 대각선에 있는 것만 1, 나머지 모두 0
    + I << 로 표현한다.
- Diagonal matrics
    + 대각선에 있는 수
    + non-zero
- Off-Diagonal matrics
    + 대각선 이외의 수

In [1]:
import numpy as np


In [3]:
np.eye(3)   # identity matrics

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [5]:
np.zeros((3,4)) # All zero matrics

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
np.full((5,2),17)  # fill matrics

array([[17, 17],
       [17, 17],
       [17, 17],
       [17, 17],
       [17, 17]])

In [14]:
M = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(M)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


- assignment
    + create 3 matrics : 2x2, 2x2, 3x2
    + compute scalar-matrics multiplication
    + add all pairs of matrics

In [16]:
M1 = np.array([[1,2],[4,5]])
M2 = np.array([[3,2],[7,8]])
M3 = np.array([[0,2],[4,6],[8,10]])
print(M1)
print(M2)
print(M3)

[[1 2]
 [4 5]]
[[3 2]
 [7 8]]
[[ 0  2]
 [ 4  6]
 [ 8 10]]


In [18]:
print(M1+M2)
print(M2+M3)    # shape error

[[ 4  4]
 [11 13]]


ValueError: operands could not be broadcast together with shapes (2,2) (3,2) 

In [20]:
print(M1*M2)
print(M2*M3)    # shape error

[[ 3  4]
 [28 40]]


ValueError: operands could not be broadcast together with shapes (2,2) (3,2) 

In [21]:
print(M1/M2)
print(M2/M3)    # shape error

[[0.33333333 1.        ]
 [0.57142857 0.625     ]]


ValueError: operands could not be broadcast together with shapes (2,2) (3,2) 