# Transposing a Vector(Matrix)
column vector -> row vector

* Symmetric Matrices -> Tranpose한 것과 동일하다.


In [1]:
import numpy as np

In [2]:
v1 = np.array([2,3,-1])

print(v1)
print(v1.T) # Transpose

[ 2  3 -1]
[ 2  3 -1]


In [4]:
v1 = np.array([2,3,-1], ndmin=2)

print(v1)
print(' ')
print(v1.T) # Transpose : row vector -> column vector

[[ 2  3 -1]]
 
[[ 2]
 [ 3]
 [-1]]


In [10]:
M = np.round(10*np.random.randn(3,3))    # random
print(M)
print(' ')
print(M.T)  # Transpose : row vector -> column vector

[[-31.  -4.  -4.]
 [ -1.   1.  -7.]
 [ 10.  -9.  22.]]
 
[[-31.  -1.  10.]
 [ -4.   1.  -9.]
 [ -4.  -7.  22.]]


- assignment         
    1) what happens when we transpose twice? -> M matricx, MT transpose, MTT double transpose      
    2) confirm that the transpose operation works on non-squre matricx      
    

In [16]:
# 1)
M = np.round(10*np.random.randn(4,4))
print(M)
print(" ")

MT = M.T
print(MT)
print(" ")

MTT = MT.T
print(MTT)  # 다시 원래 상태로 돌아간다.

[[-10.   3. -14.  -8.]
 [ -8.  -8.  -6. -31.]
 [ 13.   1.   5.   0.]
 [ 14.  11.   2.  -7.]]
 
[[-10.  -8.  13.  14.]
 [  3.  -8.   1.  11.]
 [-14.  -6.   5.   2.]
 [ -8. -31.   0.  -7.]]
 
[[-10.   3. -14.  -8.]
 [ -8.  -8.  -6. -31.]
 [ 13.   1.   5.   0.]
 [ 14.  11.   2.  -7.]]


In [21]:
# 2)
m = np.round(10*np.random.randn(2,4))
print(m)
print(' ')

mt = m.T
print(mt)
print(' ')

mtt = mt.T
print(mtt)

[[ 3. 12. 12. -7.]
 [ 5. -4. -6.  2.]]
 
[[ 3.  5.]
 [12. -4.]
 [12. -6.]
 [-7.  2.]]
 
[[ 3. 12. 12. -7.]
 [ 5. -4. -6.  2.]]
