When can be mulitple two matrices?           
AB != BA       

---
모양          
(M x N) * (N x K) = (M x K)             
ex. (5x2) * (2x7) = (5x7) -> 가능           
ex. (2x7) * (5x2) = -> 불가능         

In [1]:
import numpy as np

In [6]:
M1 = np.random.randn(4,5)   # 4x5
M2 = np.random.randn(4,5)   # 4x5

# print( np.matmul(M1, M2))   # shape error : (n?,k),(k,m?)->(n?,m?)
print( np.matmul(M1, M2.T) )
print(' ')

print(M1@M2.T)
print(' ')

print(np.matmul(M1, M2.T) - M1@M2.T)     # same result

[[ 3.22297548  0.95763055 -2.81042887  1.60514426]
 [-1.26463171 -1.37202834  2.60459718 -3.14125371]
 [-0.04336421 -2.2725318   0.89755309 -5.56930881]
 [ 0.59186103  1.46369866 -0.27360799  1.16153352]]
 
[[ 3.22297548  0.95763055 -2.81042887  1.60514426]
 [-1.26463171 -1.37202834  2.60459718 -3.14125371]
 [-0.04336421 -2.2725318   0.89755309 -5.56930881]
 [ 0.59186103  1.46369866 -0.27360799  1.16153352]]
 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


- assignment            
    1) create a 3x3 matrix of integers                
    2) multiply by (1) identity, (2) zeros, (3) that matrix's transpose              

In [21]:
M3 = np.random.randint(-10,10,size=(3,3))
print(M3)
print(' ')
M_identity = np.eye(3)
print(M_identity)
print(' ')
M_zero = np.zeros((3,3))
print(M_zero)
print(' ')
M_T = M3.T
print(M_T)

[[-1 -6 -6]
 [-1  6  9]
 [ 7  5 -6]]
 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
 
[[-1 -1  7]
 [-6  6  5]
 [-6  9 -6]]


In [22]:
print(np.matmul(M3, M_identity))
print(np.matmul(M3, M_zero))
print(np.matmul(M3, M_T))

[[-1. -6. -6.]
 [-1.  6.  9.]
 [ 7.  5. -6.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[ 73 -89  -1]
 [-89 118 -31]
 [ -1 -31 110]]
